"""add_parsed_content_to_documents

Revision ID: e37ce464becf
Revises: 8a61566dae48
Create Date: 2026-09-28 01:17:46.001338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e37ce464becf'
down_revision: Union[str, Sequence[str], None] = '8a61566dae48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('word_count', sa.BigInteger(), nullable=True))
    op.add_column('documents', sa.Column('char_count', sa.BigInteger(), nullable=True))
    op.add_column('documents', sa.Column('total_pages', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'total_pages')
    op.drop_column('documents', 'char_count')
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'parsed_content')
    # ### end Alembic commands ###
